@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

abstract class Logger {
+{abstract}CreateLogger(): LoggerType
}
note left: LoggerType stdiologger = CreateLogger()\nstdiologger.Log()

class StdioLogger {
+CreateLogger(): LoggerType
}
note bottom: return new LoggerTypeStdio

class FileLogger {
+CreateLogger(): LoggerType
}

class SyslogLogger {
+CreateLogger(): LoggerType
}

interface LoggerType {
+{abstract}Log()
}

class LoggerTypeStdio {
+Log()
}

class LoggerTypeFile {
+Log()
}

class LoggerTypeSyslog {
+Log()
}

Logger <|-- StdioLogger
Logger <|-- FileLogger
Logger <|-- SyslogLogger

Logger -> LoggerType

LoggerType <|.. LoggerTypeStdio
LoggerType <|.. LoggerTypeFile
LoggerType <|.. LoggerTypeSyslog

@enduml