@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

class StdioLogger
note left: return new LoggerTypeStdio
class FileLogger
class SyslogLogger
abstract class Logger
note left: LoggerType stdiologger = CreateLogger()\nstdiologger.Log()
interface LoggerType
class LoggerTypeStdio
class LoggerTypeFile
class LoggerTypeSyslog

Logger<|-- FileLogger
Logger<|-- StdioLogger
Logger<|-- SyslogLogger

Logger -> LoggerType

LoggerType <|.. LoggerTypeStdio
LoggerType <|.. LoggerTypeFile
LoggerType <|.. LoggerTypeSyslog

abstract class Logger {
+Log()
+{abstract}CreateLogger(): LoggerType
}

interface LoggerType {
+{abstract}Log()
}

class LoggerTypeFile {
+Log()
}

class LoggerTypeStdio {
+Log()
}

class LoggerTypeSyslog {
+Log()
}

class StdioLogger {
+CreateLogger(): LoggerType
}

class FileLogger {
+CreateLogger(): LoggerType
}

class SyslogLogger {
+CreateLogger(): LoggerType
}
@enduml